### PR TITLE
already downloaded files wouldnt be downloaded again -2 pulled the content

### PR DESCRIPTION
**Pull request by girishramnani**

### CODE REVIEW

**Comment by puneet24** [comment]
Sync with master in order to resolve the conflicts. Yes already downloaded files should not be downloaded again. So we will go with this approach.

**Comment by girishramnani** [comment]
Ok

**Comment by girishramnani** [comment]
Shouldnt we make the file structure obeying a ruby project .
Having a rakefile and lib folder

**Comment by puneet24** [comment]
Actually I was thinking to convert it into a gem. That will be better and it comprises of all the files like rakefile, lib and the most important test cases.

**Comment by girishramnani** [comment]
pulled the content

**Pull request merged**
